import { useState, useMemo } from "react";
import type { PersonProfile, WikiStatus, DraftAudit } from "../types";
import { getDraftDestination } from "../workflow";
import DraftPreview from "./DraftPreview";
import DraftLinks from "./DraftLinks";
import DraftQa from "./DraftQa";
import ArticleProposalView from "./ArticleProposal";

interface Props {
  profile: PersonProfile;
  wikiStatus: WikiStatus;
  draftAudit: DraftAudit | null;
  onGenerateDraft: () => Promise<void>;
  drafting: boolean;
  draftError: string | null;
}

type OutputSubTab = "preview" | "wikitext" | "dossier" | "audit";

export default function DraftAndOutputs({
  profile,
  wikiStatus,
  draftAudit,
  onGenerateDraft,
  drafting,
  draftError,
}: Props) {
  const [subTab, setSubTab] = useState<OutputSubTab>("preview");
  const [wikitextLang, setWikitextLang] = useState<"en" | "hi">("en");
  const [copied, setCopied] = useState(false);
  const [copiedAfc, setCopiedAfc] = useState(false);
  const [copiedDossier, setCopiedDossier] = useState(false);

  const wikitextEn = profile.wikitext_en ?? "";
  const wikitextHi = profile.wikitext_hi ?? "";
  const hasDraft = Boolean(wikitextEn || wikitextHi);
  const draftDestination = getDraftDestination(wikiStatus);

  // Generate clean Markdown dossier
  const markdownDossier = useMemo(() => {
    const lines: string[] = [];
    lines.push(`# Research Dossier: ${profile.name}`);
    lines.push(`*Generated by Wikimaker Biographical Research Workbench*\n`);

    lines.push(`## 1. Quick Facts`);
    if (profile.field) lines.push(`- **Field**: ${profile.field}`);
    if (profile.affiliation) lines.push(`- **Affiliation**: ${profile.affiliation}`);
    if (profile.nationality) lines.push(`- **Nationality**: ${profile.nationality}`);
    if (profile.birth_date) lines.push(`- **Birth Date**: ${profile.birth_date}`);
    if (profile.birth_place) lines.push(`- **Birth Place**: ${profile.birth_place}`);
    if (profile.wikidata_id) lines.push(`- **Wikidata ID**: [${profile.wikidata_id}](https://www.wikidata.org/wiki/${profile.wikidata_id})`);

    const ids = profile.confirmed_ids || profile.researcher_ids || {};
    if (Object.keys(ids).length > 0) {
      lines.push(`- **Identifiers**:`);
      for (const [k, v] of Object.entries(ids)) {
        lines.push(`  - ${k.toUpperCase()}: ${v}`);
      }
    }
    lines.push("");

    lines.push(`## 2. Collected Facts (${profile.claims.length} total)`);
    const approved = profile.claims.filter(c => c.draft_approved);
    const researchOnly = profile.claims.filter(c => !c.draft_approved);

    if (approved.length > 0) {
      lines.push(`### Draft-Approved Facts (${approved.length})`);
      for (const c of approved) {
        const src = c.source_url ? ` ([Source](${c.source_url}))` : "";
        lines.push(`- **[${c.field}]** ${c.text}${src}`);
      }
      lines.push("");
    }

    if (researchOnly.length > 0) {
      lines.push(`### Research Dossier Facts (${researchOnly.length})`);
      for (const c of researchOnly) {
        const src = c.source_url ? ` ([Source](${c.source_url}))` : "";
        lines.push(`- **[${c.field}]** ${c.text}${src}`);
      }
      lines.push("");
    }

    lines.push(`## 3. Sources Index (${profile.sources.length} active)`);
    profile.sources.forEach((s, i) => {
      const pub = s.publisher ? ` · *${s.publisher}*` : "";
      const date = s.date ? ` (${s.date})` : "";
      lines.push(`${i + 1}. [${s.title || s.url}](${s.url})${pub}${date}`);
    });

    return lines.join("\n");
  }, [profile]);

  function handleCopyWikitext(text: string) {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(text).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      });
    }
  }

  function handleCopyAfc(text: string) {
    if (navigator.clipboard) {
      const afcText = text.startsWith("{{subst:submit}}") ? text : `{{subst:submit}}\n${text}`;
      navigator.clipboard.writeText(afcText).then(() => {
        setCopiedAfc(true);
        setTimeout(() => setCopiedAfc(false), 2000);
      });
    }
  }

  function handleCopyDossier() {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(markdownDossier).then(() => {
        setCopiedDossier(true);
        setTimeout(() => setCopiedDossier(false), 2000);
      });
    }
  }

  function handleDownloadDossier() {
    const blob = new Blob([markdownDossier], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${profile.name.replace(/\s+/g, "_")}_Research_Dossier.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  const isArticleExisting = wikiStatus.status === "exists";
  const activeWikitext = wikitextLang === "hi" ? wikitextHi : wikitextEn;

  return (
    <div className="draft-and-outputs" style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {/* Draft Readiness & Action Header */}
      <div
        className="card"
        style={{
          padding: "16px 20px",
          background: "#ffffff",
          border: "1px solid var(--border)",
        }}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 14 }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
              <h2 style={{ fontSize: 17, fontWeight: 800, margin: 0 }}>
                Outputs &amp; Publication
              </h2>
              {draftAudit && (
                <span
                  style={{
                    fontSize: 11,
                    fontWeight: 700,
                    padding: "2px 8px",
                    borderRadius: 12,
                    background: draftAudit.ready ? "#dcfce7" : "#fee2e2",
                    color: draftAudit.ready ? "#15803d" : "#b91c1c",
                    border: draftAudit.ready ? "1px solid #86efac" : "1px solid #fca5a5",
                  }}
                >
                  {draftAudit.ready ? "✓ Ready to Submit" : `⚠️ ${draftAudit.blockers.length} Blocker(s)`}
                </span>
              )}
            </div>
            <p style={{ fontSize: 12, color: "var(--muted)", margin: 0 }}>
              {draftAudit?.ready
                ? `Cleared AfC gate: ${draftAudit.eligible_source_count} eligible citations (${draftAudit.independent_source_count} independent secondary).`
                : "Deterministic wikitext generated from approved claims and verified sources."}
            </p>
          </div>

          <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
            <button
              type="button"
              className="btn-primary"
              onClick={onGenerateDraft}
              disabled={drafting || (draftAudit !== null && !draftAudit.ready)}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 6,
                padding: "8px 16px",
                fontSize: 13,
              }}
            >
              {drafting ? "Rendering Draft…" : hasDraft ? "🔄 Re-render Draft" : "✨ Generate AfC Draft"}
            </button>
            <button
              type="button"
              className="btn-ghost"
              onClick={handleDownloadDossier}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 6,
                padding: "8px 14px",
                fontSize: 12,
              }}
            >
              📥 Download Dossier (.md)
            </button>
          </div>
        </div>

        {/* Actionable Blockers Callout */}
        {draftAudit && !draftAudit.ready && draftAudit.blockers.length > 0 && (
          <div
            style={{
              marginTop: 12,
              padding: "10px 14px",
              background: "#fffbeb",
              border: "1px solid #fcd34d",
              borderRadius: 8,
              fontSize: 12,
              color: "#92400e",
            }}
          >
            <strong>To unlock draft generation:</strong>
            <ul style={{ margin: "4px 0 0 16px", padding: 0 }}>
              {draftAudit.blockers.map((b, i) => (
                <li key={i}>{b.message || b.code}</li>
              ))}
            </ul>
          </div>
        )}

        {draftError && (
          <div style={{ marginTop: 12, padding: "10px 14px", background: "#fee2e2", border: "1px solid #fca5a5", borderRadius: 8, color: "var(--danger)", fontSize: 12 }}>
            {draftError}
          </div>
        )}
      </div>

      {/* Simplified 4 Sub-Tabs */}
      <div style={{ display: "flex", gap: 4, borderBottom: "1px solid var(--border)" }}>
        {[
          { id: "preview" as const, label: "Draft Preview", icon: "👁️" },
          { id: "wikitext" as const, label: "Wikitext", icon: "📋" },
          { id: "dossier" as const, label: "Research Dossier", icon: "📑" },
          { id: "audit" as const, label: "Evidence & Pre-flight Audit", icon: "🛡️" },
        ].map(tab => {
          const active = subTab === tab.id;
          return (
            <button
              key={tab.id}
              type="button"
              onClick={() => setSubTab(tab.id)}
              style={{
                padding: "8px 14px",
                fontSize: 13,
                fontWeight: active ? 700 : 500,
                background: "none",
                border: "none",
                cursor: "pointer",
                borderBottom: active ? "2px solid var(--primary)" : "2px solid transparent",
                color: active ? "var(--primary)" : "var(--muted)",
                display: "flex",
                alignItems: "center",
                gap: 6,
              }}
            >
              <span>{tab.icon}</span>
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Sub-Tab 1: Draft Preview */}
      {subTab === "preview" && (
        <div className="card" style={{ padding: "20px" }}>
          {!hasDraft ? (
            <div style={{ textAlign: "center", padding: "28px 0", color: "var(--muted)" }}>
              <p style={{ fontSize: 24, marginBottom: 6 }}>📝</p>
              <h4 style={{ fontSize: 15, fontWeight: 700, color: "var(--text)", marginBottom: 4 }}>
                No draft rendered yet
              </h4>
              <p style={{ fontSize: 13, marginBottom: 12 }}>
                Click &quot;Generate AfC Draft&quot; above to render strictly verified wikitext from approved claims.
              </p>
              <button
                type="button"
                className="btn-primary"
                onClick={onGenerateDraft}
                disabled={drafting || (draftAudit !== null && !draftAudit.ready)}
                style={{ fontSize: 13 }}
              >
                {drafting ? "Rendering…" : "Generate Draft Now"}
              </button>
            </div>
          ) : (
            <>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>
                  Target: <strong>{draftDestination.label}</strong>
                </span>
                <div style={{ display: "flex", gap: 6 }}>
                  <button
                    type="button"
                    className="btn-ghost"
                    onClick={() => handleCopyWikitext(wikitextEn)}
                    style={{ fontSize: 12, padding: "4px 10px" }}
                  >
                    {copied ? "✓ Copied" : "Copy Wikitext"}
                  </button>
                  <button
                    type="button"
                    className="btn-primary"
                    onClick={() => handleCopyAfc(wikitextEn)}
                    style={{ fontSize: 12, padding: "4px 10px" }}
                  >
                    {copiedAfc ? "✓ Copied with {{subst:submit}}" : "Copy with {{subst:submit}}"}
                  </button>
                </div>
              </div>
              <DraftPreview
                profileName={profile.name}
                wikitext={wikitextEn}
                draftDestination={draftDestination}
              />
            </>
          )}
        </div>
      )}

      {/* Sub-Tab 2: Clean Wikitext Source */}
      {subTab === "wikitext" && (
        <div className="card" style={{ padding: "20px" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12, flexWrap: "wrap", gap: 8 }}>
            <div style={{ display: "flex", gap: 6 }}>
              <button
                type="button"
                className={wikitextLang === "en" ? "btn-primary" : "btn-ghost"}
                onClick={() => setWikitextLang("en")}
                style={{ fontSize: 12, padding: "4px 12px" }}
              >
                🇬🇧 English Wikitext
              </button>
              {wikitextHi && (
                <button
                  type="button"
                  className={wikitextLang === "hi" ? "btn-primary" : "btn-ghost"}
                  onClick={() => setWikitextLang("hi")}
                  style={{ fontSize: 12, padding: "4px 12px" }}
                >
                  🇮🇳 Hindi Wikitext
                </button>
              )}
            </div>

            <div style={{ display: "flex", gap: 6 }}>
              <button
                type="button"
                className="btn-ghost"
                onClick={() => handleCopyWikitext(activeWikitext)}
                disabled={!activeWikitext}
                style={{ fontSize: 12, padding: "4px 10px" }}
              >
                {copied ? "✓ Copied" : "Copy Raw Wikitext"}
              </button>
              <button
                type="button"
                className="btn-primary"
                onClick={() => handleCopyAfc(activeWikitext)}
                disabled={!activeWikitext}
                style={{ fontSize: 12, padding: "4px 10px" }}
              >
                {copiedAfc ? "✓ Copied with {{subst:submit}}" : "Copy with {{subst:submit}}"}
              </button>
            </div>
          </div>

          {!activeWikitext ? (
            <p style={{ color: "var(--muted)", fontSize: 13, textAlign: "center", padding: "20px 0" }}>
              No wikitext rendered yet. Click &quot;Generate AfC Draft&quot; above.
            </p>
          ) : (
            <pre
              style={{
                background: "var(--bg)",
                padding: "14px",
                borderRadius: 8,
                fontSize: 12,
                overflowX: "auto",
                whiteSpace: "pre-wrap",
                fontFamily: "monospace",
                lineHeight: 1.5,
                maxHeight: "65vh",
              }}
            >
              {activeWikitext}
            </pre>
          )}
        </div>
      )}

      {/* Sub-Tab 3: Research Dossier (Markdown) */}
      {subTab === "dossier" && (
        <div className="card" style={{ padding: "20px" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
            <span style={{ fontSize: 12, color: "var(--muted)" }}>
              Complete offline markdown dossier with all verified facts and source citations.
            </span>
            <div style={{ display: "flex", gap: 6 }}>
              <button
                type="button"
                className="btn-ghost"
                onClick={handleCopyDossier}
                style={{ fontSize: 12, padding: "4px 10px" }}
              >
                {copiedDossier ? "✓ Copied Markdown" : "Copy Markdown"}
              </button>
              <button
                type="button"
                className="btn-primary"
                onClick={handleDownloadDossier}
                style={{ fontSize: 12, padding: "4px 10px" }}
              >
                📥 Download .md
              </button>
            </div>
          </div>

          <pre
            style={{
              background: "var(--bg)",
              padding: "14px",
              borderRadius: 8,
              fontSize: 12,
              overflowX: "auto",
              whiteSpace: "pre-wrap",
              fontFamily: "monospace",
              lineHeight: 1.5,
              maxHeight: "65vh",
            }}
          >
            {markdownDossier}
          </pre>
        </div>
      )}

      {/* Sub-Tab 4: Combined Evidence & Pre-flight Audit */}
      {subTab === "audit" && (
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <div className="card" style={{ padding: "18px" }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 10 }}>
              🛡️ AfC Pre-flight Quality Gate
            </h3>
            <DraftQa profileName={profile.name} />
          </div>

          <div className="card" style={{ padding: "18px" }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 10 }}>
              🔗 Citation Provenance &amp; Verification Links
            </h3>
            <DraftLinks profileName={profile.name} />
          </div>

          {isArticleExisting && (
            <div className="card" style={{ padding: "18px" }}>
              <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 10 }}>
                📝 Existing Wikipedia Article Proposal
              </h3>
              <ArticleProposalView profileName={profile.name} />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
